mod.addBlock("meatchunkBlock.js", "normal");
mod.addBlock("meatWood.js", "normal");
mod.addBlock("meatLeaf.js", "normal");
mod.addBlock("taintedWood.js", "normal");
mod.addBlock("deadWood.js", "normal");
mod.addBlock("OverworldLeaves.js", "normal");
mod.addBlock("overworldtrees.js", "normal");
mod.addBlock("SpecialOres.js", "normal");
mod.addBlock("InfiniOres.js", "normal");
mod.addBlock("specialingredBs.js", "normal");
mod.addItem("silvernugget.js", "normal");
mod.addItem("specialnuggets.js", "normal");
mod.addItem("woodchunk.js", "normal");
mod.addItem("Irium Axe.js", "normal");
mod.addItem("POre.js", "normal");
mod.addItem("Netherstarforms.js", "normal");
mod.addItem("specialingredIs.js", "normal");
mod.addItem("OreJ.js", "normal");
mod.addToOreDictionary( "oreInfinium", "BanjoPackAlpha:InfiniXores:0" );
mod.addToOreDictionary( "oreClustHoDU", "BanjoPackAlpha:InfiniXores:1" );
mod.addToOreDictionary( "oreClustHoD1", "BanjoPackAlpha:InfiniXores:2" );
mod.addToOreDictionary( "oreClustHoD2", "BanjoPackAlpha:InfiniXores:3" );
mod.addToOreDictionary( "oreClustHoD3", "BanjoPackAlpha:InfiniXores:4" );
mod.addToOreDictionary( "oreClustHeart", "BanjoPackAlpha:banjoOres:0" );
mod.addToOreDictionary( "oreClustBizz1", "BanjoPackAlpha:banjoOres:1" );
mod.addToOreDictionary( "oreClustBizz2", "BanjoPackAlpha:banjoOres:2" );
mod.addToOreDictionary( "oreClustEye", "BanjoPackAlpha:banjoOres:3" );
mod.addToOreDictionary( "oreClustDark1", "BanjoPackAlpha:banjoOres:4" );
mod.addToOreDictionary( "oreClustDark2", "BanjoPackAlpha:banjoOres:5" );
mod.addToOreDictionary( "oreClustIce1", "BanjoPackAlpha:banjoOres:6" );
mod.addToOreDictionary( "oreClustIce2", "BanjoPackAlpha:banjoOres:7" );
mod.addToOreDictionary( "oreClustIce3", "BanjoPackAlpha:banjoOres:8" );
mod.addToOreDictionary( "oreClustIce4", "BanjoPackAlpha:banjoOres:9" );
mod.addToOreDictionary( "oreClustIce5", "BanjoPackAlpha:banjoOres:10" );
mod.addToOreDictionary( "oreClustObsid1", "BanjoPackAlpha:banjoOres:11" );
mod.addToOreDictionary( "oreClustObsid2", "BanjoPackAlpha:banjoOres:12" );
mod.addToOreDictionary( "oreClustObsid3", "BanjoPackAlpha:banjoOres:13" );
mod.addToOreDictionary( "oreClustObsid4", "BanjoPackAlpha:banjoOres:14" );
mod.addWorldGen("Infiniore1.js", "ore");
mod.addWorldGen("Infiniore2.js", "ore");
mod.addWorldGen("Infiniore3.js", "ore");
mod.addWorldGen("Infiniore4.js", "ore");
mod.addWorldGen("Infiniore5.js", "ore");
mod.addWorldGen("Infiniore6.js", "ore");
mod.addWorldGen("Infiniore7.js", "ore");
mod.addWorldGen("Infiniore8.js", "ore");
mod.addWorldGen("Infiniore9.js", "ore");
mod.addWorldGen("Infiniore10.js", "ore");
mod.addWorldGen("Infiniore11.js", "ore");
mod.addSmeltingRecipeFor("Xtrimulator1", "BanjoPackAlpha:specialingredIs:5 1", "Thaumcraft:ItemShard:5");
mod.addSmeltingRecipeFor("Xtrimulator1", "minecraft:emerald 3", "BanjoPackAlpha:specialingredIs:1");
mod.addSmeltingRecipeFor("Xtrimulator1", "BanjoPackAlpha:PurifiedItems:6 4", "minecraft:diamond");
mod.addSmeltingRecipeFor("Xtrimulator1", "minecraft:clay 3", "minecraft:sandstone");
mod.addSmeltingRecipeFor("Xtrimulator1", "minecraft:glowstone_dust 1", "minecraft:redstone");
mod.addSmeltingRecipeFor("Xtrimulator1", "BanjoPackAlpha:PurifiedItems 1", "minecraft:iron_ore");
mod.addSmeltingRecipeFor("Xtrimulator1", "BanjoPackAlpha:PurifiedItems:2 1", "minecraft:skull");
mod.addSmeltingRecipeFor("Xtrimulator1", "BanjoPackAlpha:PurifiedItems:5 1", "minecraft:golden_apple");
mod.addSmeltingRecipeFor("Xtrimulator1", "minecraft:quartz 1", "appliedenergistics2:item.ItemMultiMaterial");
mod.addSmeltingRecipeFor("evilR", "BanjoPackAlpha:Stars:1 1", "BanjoPackAlpha:Stars:0");
mod.addSmeltingRecipeFor("evilR", "BanjoPackAlpha:specialingredIs:8 1", "BanjoPackAlpha:specialingredIs:5");
mod.addSmeltingRecipeFor("exileR", "BanjoPackAlpha:specialingredIs:6 1", "BanjoPackAlpha:specialingredIs:5");
mod.addSmeltingRecipeFor("exileR", "witchery:ingredient:99 1", "Natura:barleyFood:3");
mod.addSmeltingRecipeFor("exileR", "witchery:somniancotton 1", "witchery:ingredient:99");
mod.addSmeltingRecipeFor("exileR", "witchery:ingredient:96 1", "minecraft:potion:16428");
mod.addSmeltingRecipeFor("exileR", "witchery:ingredient:103 1", "TConstruct:buckets:16");
mod.addSmeltingRecipeFor("exileR", "witchery:ingredient:112 1", "witchery:ingredient:103");
mod.addFuelFor("evilF", "necromancy:BucketBlood", 20000);
mod.addFuelFor("exileF", "minecraft:ender_pearl", 2);
mod.addFuelFor("exileF", "BanjoPackAlpha:specialingredIs:2", 20);
mod.addFuelFor("exileF", "BanjoPackAlpha:specialingredIs:3", 200);
mod.addFuelFor("exileF", "BanjoPackAlpha:specialingredIs:4", 2000);
mod.addFuelFor("exileF", "BanjoPackAlpha:specialingredBs1:0", 50000);
mod.addFuelFor("Redstoned", "minecraft:redstone", 400);
mod.addTileEntity("InfiniXtrimulatorTE.js", "furnace");
mod.addTileEntity("InfiniXtrifelatorTE.js", "furnace");
mod.addTileEntity("InfiniXilifierTE.js", "furnace");
mod.addGui("InfiniXtrimulatorGUI.js", "furnace");
mod.addBlock("InfiniXtrimulator.js", "furnace");
mod.addBlock("InfiniXtrifelator.js", "furnace");
mod.addBlock("InfiniXilifier.js", "furnace");
mod.addRecipe("Thaumcraft:blockCosmeticSolid 16", 3, 3, "Thaumcraft:ItemShard:1", "minecraft:nether_star", "Thaumcraft:ItemShard:2", "Thaumcraft:ItemShard:0", "minecraft:obsidian", "Thaumcraft:ItemShard:3", "minecraft:nether_star", "Thaumcraft:ItemShard:4", "minecraft:nether_star");
mod.addRecipe("BanjoPackAlpha:specialingredIs:1 1", 3, 3, "BanjoPackAlpha:specialingredIs:0", "BanjoPackAlpha:specialingredIs:0", "BanjoPackAlpha:specialingredIs:0", "BanjoPackAlpha:specialingredIs:0", "BanjoPackAlpha:PurifiedItems:6", "BanjoPackAlpha:specialingredIs:0", "BanjoPackAlpha:specialingredIs:0", "BanjoPackAlpha:specialingredIs:0", "BanjoPackAlpha:specialingredIs:0");
mod.addRecipe("BanjoPackAlpha:specialingredIs 1", 3, 3, "BanjoPackAlpha:specialingredBs1:4", "BanjoPackAlpha:specialingredBs1:4", "BanjoPackAlpha:specialingredBs1:4", "BanjoPackAlpha:specialingredBs1:4", "BanjoPackAlpha:PurifiedItems:0", "BanjoPackAlpha:specialingredBs1:4", "BanjoPackAlpha:specialingredBs1:4", "BanjoPackAlpha:specialingredBs1:4", "BanjoPackAlpha:specialingredBs1:4");
mod.addRecipe("BanjoPackAlpha:specialingredBs1:4 1", 3, 3, "minecraft:grass", "minecraft:grass", "minecraft:grass", "minecraft:grass", "BanjoPackAlpha:specialingredBs1:3", "minecraft:grass", "minecraft:grass", "minecraft:grass", "minecraft:grass");
mod.addRecipe("minecraft:netherrack 64", 3, 3, "BanjoPackAlpha:PurifiedItems:2", "minecraft:dirt", "minecraft:glowstone_dust", "minecraft:gravel", "minecraft:sand", "minecraft:glowstone_dust", "minecraft:glowstone_dust", "minecraft:glowstone_dust", "minecraft:glowstone_dust");
mod.addRecipe("BanjoPackAlpha:PurifiedItems:4", 3, 3, "minecraft:obsidian", "minecraft:glowstone", "minecraft:obsidian", "BanjoPackAlpha:PurifiedItems:2", "BanjoPackAlpha:PurifiedItems:2", "BanjoPackAlpha:PurifiedItems:2", "minecraft:obsidian", "minecraft:redstone_block", "minecraft:obsidian");
mod.addRecipe("BanjoPackAlpha:Stars", 3, 3, "BanjoPackAlpha:PurifiedItems:4", "minecraft:netherrack", "BanjoPackAlpha:PurifiedItems:4", "minecraft:netherrack", "BanjoPackAlpha:PurifiedItems:4", "minecraft:netherrack", "BanjoPackAlpha:PurifiedItems:4", "minecraft:netherrack", "BanjoPackAlpha:PurifiedItems:4");
mod.addRecipe("minecraft:ender_pearl 36", 3, 3, "BanjoPackAlpha:PurifiedItems:0", "minecraft:diamond", "BanjoPackAlpha:PurifiedItems:0", "minecraft:diamond", "BanjoPackAlpha:PurifiedItems:5", "minecraft:diamond", "BanjoPackAlpha:PurifiedItems:0", "minecraft:diamond", "BanjoPackAlpha:PurifiedItems:0");
mod.addRecipe("BanjoPackAlpha:InfiniXtrimulator", 3, 3, "minecraft:redstone_block", "minecraft:diamond_block", "minecraft:iron_block", "minecraft:furnace", "minecraft:coal_block", "minecraft:furnace", "minecraft:gold_block", "minecraft:diamond_block", "appliedenergistics2:tile.BlockQuartz");
mod.addRecipe("TConstruct:materials:8", 3, 3, "BanjoPackAlpha:PurifiedItems:4", "minecraft:nether_star", "BanjoPackAlpha:PurifiedItems:4", "minecraft:nether_star", "minecraft:bone", "minecraft:nether_star", "BanjoPackAlpha:PurifiedItems:4", "minecraft:nether_star", "BanjoPackAlpha:PurifiedItems:4");
mod.addRecipe("minecraft:nether_star", 3, 3, "minecraft:quartz_block", "minecraft:gold_block", "minecraft:quartz_block", ":blockSilver", "BanjoPackAlpha:Stars:1", ":blockSilver", "minecraft:quartz_block", "minecraft:gold_block", "minecraft:quartz_block");
mod.addRecipe("BanjoPackAlpha:InfiniXtrifelator", 3, 3, "BanjoPackAlpha:Stars:0", "minecraft:obsidian", "BanjoPackAlpha:Stars:0", "minecraft:obsidian", "bluepower:ruby_block", "minecraft:obsidian", "BanjoPackAlpha:Stars:0", "minecraft:obsidian", "BanjoPackAlpha:Stars:0");
mod.addRecipe("BanjoPackAlpha:specialingredBs1:3 1", 3, 3, "minecraft:flint", "minecraft:flint", "minecraft:flint", "minecraft:flint", "minecraft:flint", "minecraft:flint", "minecraft:flint", "minecraft:flint", "minecraft:flint");
mod.addRecipe("ThaumicTinkerer:kamiResource:6 4", 3, 3, "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:specialingredIs:8", "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:specialingredBs1:2", "BanjoPackAlpha:specialingredIs:8", "BanjoPackAlpha:specialingredBs1:2", "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:specialingredIs:8", "Thaumcraft:blockCosmeticSolid:0");
mod.addRecipe("ThaumicTinkerer:kamiResource:7 4", 3, 3, "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:specialingredIs:6", "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:specialingredBs1:1", "BanjoPackAlpha:specialingredIs:6", "BanjoPackAlpha:specialingredBs1:1", "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:specialingredIs:6", "Thaumcraft:blockCosmeticSolid:0");
mod.addRecipe("BanjoPackAlpha:specialingredBs1:0 1", 3, 3, "minecraft:nether_star", "minecraft:nether_star", "minecraft:nether_star", "minecraft:nether_star", "Thaumcraft:blockCosmeticSolid:0", "minecraft:nether_star", "minecraft:nether_star", "minecraft:nether_star", "minecraft:nether_star");
mod.addRecipe("BanjoPackAlpha:specialingredBs1:1 1", 3, 3, "BanjoPackAlpha:specialingredIs:4", "BanjoPackAlpha:specialingredIs:4", "BanjoPackAlpha:specialingredIs:4", "BanjoPackAlpha:specialingredIs:4", "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:specialingredIs:4", "BanjoPackAlpha:specialingredIs:4", "BanjoPackAlpha:specialingredIs:4", "BanjoPackAlpha:specialingredIs:4");
mod.addRecipe("BanjoPackAlpha:specialingredIs:4 1", 3, 3, "BanjoPackAlpha:specialingredIs:3", "BanjoPackAlpha:specialingredIs:3", "BanjoPackAlpha:specialingredIs:3", "BanjoPackAlpha:specialingredIs:3", "BanjoPackAlpha:specialingredIs:3", "BanjoPackAlpha:specialingredIs:3", "BanjoPackAlpha:specialingredIs:3", "BanjoPackAlpha:specialingredIs:3", "BanjoPackAlpha:specialingredIs:3");
mod.addRecipe("BanjoPackAlpha:specialingredIs:3 1", 3, 3, "BanjoPackAlpha:specialingredIs:2", "BanjoPackAlpha:specialingredIs:2", "BanjoPackAlpha:specialingredIs:2", "BanjoPackAlpha:specialingredIs:2", "BanjoPackAlpha:specialingredIs:2", "BanjoPackAlpha:specialingredIs:2", "BanjoPackAlpha:specialingredIs:2", "BanjoPackAlpha:specialingredIs:2", "BanjoPackAlpha:specialingredIs:2");
mod.addRecipe("BanjoPackAlpha:specialingredIs:2 1", 3, 3, "minecraft:ender_pearl", "minecraft:ender_pearl", "minecraft:ender_pearl", "minecraft:ender_pearl", "minecraft:ender_pearl", "minecraft:ender_pearl", "minecraft:ender_pearl", "minecraft:ender_pearl", "minecraft:ender_pearl");
mod.addRecipe("BanjoPackAlpha:specialingredBs1:2 1", 3, 3, "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:specialingredBs1:0", "Thaumcraft:blockCosmeticSolid:0", "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:specialingredBs1:0", "Thaumcraft:blockCosmeticSolid:0", "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:specialingredBs1:0", "Thaumcraft:blockCosmeticSolid:0");
mod.addRecipe("BanjoPackAlpha:InfiniXilifier", 3, 3, "Thaumcraft:blockCosmeticSolid:0", "Thaumcraft:blockCosmeticSolid:0", "Thaumcraft:blockCosmeticSolid:0", "BanjoPackAlpha:InfiniXtrimulator", "BanjoPackAlpha:specialingredBs1:1", "BanjoPackAlpha:InfiniXtrimulator", "Thaumcraft:blockCosmeticSolid:0", "Thaumcraft:blockCosmeticSolid:0", "Thaumcraft:blockCosmeticSolid:0");
mod.addRecipe("minecraft:ghast_tear 24", 3, 3, "minecraft:glowstone_dust", "minecraft:nether_star", "minecraft:glowstone_dust", "minecraft:nether_star", "BanjoPackAlpha:PurifiedItems:2", "minecraft:nether_star", "minecraft:glowstone_dust", "minecraft:nether_star", "minecraft:glowstone_dust");